version: '3.4'

networks:
    net:

services:

### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx       
      container_name: nginx
      volumes:
        - ./nginx:/etc/nginx
      ports:
        - "80:80"
        - "443:443"
      networks:
        - net